server:
  port: 8081

spring:
  application:
    name: men-service

  datasource:
    url: jdbc:h2:mem:men_db
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.textile.men_service.controller: INFO
    com.textile.men_service.service: DEBUG
